### ISSUE TITLE
Connection

### ISSUE THREAD

**Issue by Septan** [xcscxr/nineanime-grabber#1]
```
E:\Temp\nineanime-grabber-main\nineanime-grabber-main>python main.py
? Enter a query or a URL: Tsubasa Chronicle
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Python310\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Python310\lib\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "C:\Python310\lib\site-packages\urllib3\connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Python310\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Python310\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Python310\lib\ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Python310\lib\ssl.py", line 1070, in _create
    self.do_handshake()
  File "C:\Python310\lib\ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Python310\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Python310\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='9anime.to', port=443): Max retries exceeded with url: /ajax/anime/search?vrf=uAqdiypGX5jKpxWiJ7Xgw8KYZogCaod0&keyword=Tsubasa+Chronicle (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Temp\nineanime-grabber-main\nineanime-grabber-main\main.py", line 143, in <module>
    run()
  File "E:\Temp\nineanime-grabber-main\nineanime-grabber-main\main.py", line 140, in run
    finder(query)
  File "E:\Temp\nineanime-grabber-main\nineanime-grabber-main\main.py", line 34, in finder
    data = search(query, **kwargs)
  File "E:\Temp\nineanime-grabber-main\nineanime-grabber-main\parsers\search_parser.py", line 66, in search
    res = client.get(url, params=params, headers=h)
  File "C:\Python310\lib\site-packages\requests\sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python310\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python310\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python310\lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='9anime.to', port=443): Max retries exceeded with url: /ajax/anime/search?vrf=uAqdiypGX5jKpxWiJ7Xgw8KYZogCaod0&keyword=Tsubasa+Chronicle (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)')))
```

**Comment by xcscxr** [comment]
The site is blocked by your ISP, use a VPN.

**Comment by Septan** [comment]
I am able to visit 9anime. I try VPN in two different locations. Furthermore, I still get the same thing.

**Comment by Septan** [comment]
The issue was malwarebytes
